### ISSUE TITLE
Forecast Weather bar disappears after updating

### ISSUE THREAD

**Issue by Shadoefax** [Geek-in-Training/Firefox-Addon-Bar--Restored#1]
Using: [The Addon Bar (restored) 3.1](https://addons.mozilla.org/en-US/firefox/addon/the-addon-bar/) and [Forecastfox 2.2.4](https://static.getforecastfox.com/downloads/forecastfox-latest.xpi).

When dragging the Forecastfox bar into the add-on bar, it remains there only until the Forecastfox weather data is reloaded.  The reloads occur automatically every few minutes or when the "_Reload weather data_" button is clicked (context menu on the Forecastfox bar) then the bar disappears.

**Comment by Geek-in-Training** [comment]
I have not been able to reproduce this problem. Does it still occur after restarting Firefox?

**Comment by Shadoefax** [comment]
Yes, it does.  I have over 50 extensions installed and tried to duplicate the issue with a fresh, clean profile.  With only The Add-on Bar (restored) and Forecastfox installed it seems to work as expected.

I will experiment with  possible extensions conflicts when I have the time.

**Comment by Shadoefax** [comment]
I believe this issue is resolved.  If I "restore all defaults" in the Forecastfox bar options, the bar remains in the add-on bar as it should.

**Comment by Geek-in-Training** [comment]
Okay, good to know.
