### ISSUE TITLE
a mistake

### ISSUE THREAD

**Issue by 999946** [Geek-in-Training/Firefox-Addon-Bar--Restored#12]
GetMigratedItems was a mistake
You should use this method.
CustomizableUI.getWidgetIdsInArea(areaName);

**Comment by Geek-in-Training** [comment]
Which `areaName` were you thinking of? The problem with using `CustomizableUI.getWidgetIdsInArea("nav-bar");` is that the user may have some icons there that they want to be there. I would also have to manually filter out things such as the home button and the downloads button.

**Comment by 999946** [comment]
CustomizableUI.getWidgetIdsInArea("GiT-addon-bar");

**Comment by Geek-in-Training** [comment]
I'm sorry, I fail to see how this would replace `getMigratedItems()`.  It returns an array of item IDs that have been migrated off the old `addon-bar` to the `nav-bar`, whereas `CustomizableUI.getWidgetIdsInArea("GiT-addon-bar");` would return an array of IDs that are already in my newly added addon bar.
