### ISSUE TITLE
Now there is now menu in Firefox

### ISSUE THREAD

**Issue by mausebaer** [Geek-in-Training/Firefox-Addon-Bar--Restored#20]
Hello,
now I have the statusbar again but no menutab more!

**Comment by Geek-in-Training** [comment]
Could you clarify I little for me  what a menutab is?  I am a little confused.

**Comment by mausebaer** [comment]
Am 24.06.2014 06:07, schrieb Geek in Training:

> Could you clarify I little for me what a menutab is? I am a little 
> confused.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Geek-in-Training/Firefox-Addon-Bar--Restored/issues/20#issuecomment-46930064.
> 
> Hello, thanks for reply. I mean the menutab of Firefox

## 

Unbenanntes Dokument

Mit freundlichen Grüßen
Günter Leipfinger

Münchner Straße 18
*85622 Feldkirchen *
Tel: 089/9032433
www.guenter-leipfinger.de http://www.guenter-leipfinger.de

**Comment by Geek-in-Training** [comment]
Hi,

If you are looking for the old Firefox menu, the only way I am aware of getting back is with Classic Theme Restorer.
