### ISSUE TITLE
Does you Addon-Bar "decide" what counts as an add-on?

### ISSUE THREAD

**Issue by annasonymous** [Geek-in-Training/Firefox-Addon-Bar--Restored#21]
I hope this makes sense...
Firefox doesn't "allow" me to add add-ons to your bar. I only have the options "add to menu" and "add to symbol bar"(might have a different name in the english version), and I can only remove add-ons from your bar by clicking "remove from symbol bar". 
Once I have removed something from your bar by clicking the aforementioned option, I can't put it back on your bar. 
I also didn't place anything on your bar to begin with, the add-ons automatically appeared on it when I installed it. 
Unfortunally, some add-ons stayed on the symbol bar and some in the menu.

So my question is:
What would I have to do to manually put add-ons on your (otherwise really great) addon-bar?

Thank you very much in advance,
Sarah
PS: I'm using version 30.0

**Comment by Geek-in-Training** [comment]
You can drag and drop any button you would like into the addon bar when you are in Customize mode.  This  page explains it pretty well: https://support.mozilla.org/kb/customize-firefox-controls-buttons-and-toolbars

**Comment by annasonymous** [comment]
Umm...no, I can't. My knowledge of the english language isn't broad enough to make it any clearer, so I  took a picture of me attempting to add an add-on to your add-on bar(which I of course did in the cotumize mode)
![imag0413](https://cloud.githubusercontent.com/assets/7995393/3420362/b0e85974-fea5-11e3-8255-6ca7ff373120.jpg)
As you can see, I am not able to add stuff to your bar. 
I hovered over every inch of it to find a place to insert that damn button, but it is NOT possible.

Thanks for your help,
Sarah

EDIT: I FOUND THE REASON IT DIDN'T WORK.
Apparently, there was a compability issue with one of the other add-ons I am using.
It STARTED TO WORK PERFECTLY after I disabled every other add-on I use to alter the appearance of Firefox. I activated them one by one to find out which one was causing the problem, but now everything works fine with all of them being activated at the same time as your add-on.

**Comment by Geek-in-Training** [comment]
Glad to hear it is working now!  That sounds like a very strange compatibility problem, though. Could you send me a list of the addons you have installed?

**Comment by annasonymous** [comment]
Hi,
sorry for the late answer.

Those are the add-ons I use(and that I disabled):
Stylish
Personas Plus
Greasemonkey
Tab Mix Plus
Classic Theme Restorer

I disabled them all, restarted FF, tried your add-on again( which was working, hooray!), and then started to enable them one by one to see which one was the problem. Turns out that when I enable your add-on first and then all the others, everything works fine.
It's a strange case, really, but maybe you can get some information out of it.

Have a nice weekend!

Glad to hear it is working now!  That sounds like a very strange compatibility problem, though. Could you send me a list of the addons you have installed?
