### ISSUE TITLE
The Addon Bar Is There But It's Blank, How Do I Add Items?

### ISSUE THREAD

**Issue by tackyjan** [Geek-in-Training/Firefox-Addon-Bar--Restored#23]
Hello All,

I installed Addon-Bar--Restored to Firefox and the Addon Bar Is There But It's Blank, How Do I Add Items? Also, how do I move it from the bottom to the top of the Firefox window?

Thank you,

~J

**Comment by Geek-in-Training** [comment]
Hi,

Sorry for the late response.

You can add items the same way you add or move any items in Firefox.  See https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars

Let me know if you still have questions!
