### ISSUE TITLE
Feature request: Display status text in the Addon bar/ Status bar, instead in a popup

### ISSUE THREAD

**Issue by Haven667** [Geek-in-Training/Firefox-Addon-Bar--Restored#26]
Hello,

would it be possible to display the status text (links, loading status,etc.) in the Addon bar/ Status bar, instead of using the default popup? Similar to the extension "Status-4-Evar". Here are screens for a better explanation:

Default popup:
![default_popup](https://cloud.githubusercontent.com/assets/9346225/6091440/5729def0-aeac-11e4-8bed-7d2d26a4e1ef.png)

Like "Status-4-Evar":
![status-4-evar](https://cloud.githubusercontent.com/assets/9346225/6091442/60c63fa8-aeac-11e4-80b2-1d5f9a8eab12.png)

Thank you very much in advance. :-)

**Comment by Geek-in-Training** [comment]
I'll look into the possibility.

Is there a particular reason not to just use status-4-evar, since it already has said feature?

**Comment by Haven667** [comment]
Sure, I could just use **Status-4-Evar** again (I used it before), but I like your extension more. It's more lightweight. **Status-4-Evar** has too much features, which I don't need.

I could understand if such an feature isn't planned or just too much for your extension, but it would be really nice.

**Comment by Geek-in-Training** [comment]
Oh okay, that makes sense.  I made this addon to be lightweight by design, trying to restore what was removed and that only.   That is the main issue with trying to add things like this; yes, they would be nice, but if I added all the "nice" features that I get requests for, suddenly it is no longer lightweight...

**Comment by Haven667** [comment]
Thank you for the answer. Like said, I really understand your point. So if you want, you can close it here.

Thanks again for your nice extension. :-)

**Comment by Geek-in-Training** [comment]
Your welcome! 

P.S.  I'll try to see what would be required to implement said feature into the addon, and, if it isn't too difficult, I could send you a modified version of "The Addon Bar (Restored)" with that feature.

**Comment by Haven667** [comment]
Oh, yes... that would be very nice. But just take your time. Thanks again.

Greets
