### ISSUE TITLE
Some buttons make bar height change - Firefox 36

### ISSUE THREAD

**Issue by careca1970** [Geek-in-Training/Firefox-Addon-Bar--Restored#27]
After updating to Firefox 36, I got surprised by a much higher addon-bar with some quite big buttons.
I could not find a way to set addon-bar height, but removing these bigger buttons, the addon-bar got back to old (normal) look.

Please, add a way to set an addon-bar height constraint!

Many thanks for your nice work!
Br, careca

**Comment by Geek-in-Training** [comment]
Hi,   Sorry for the very very late response.

I can give it a shot.

P.S.  Have you already tried the "compact mode" option?

**Comment by careca1970** [comment]
Hi, Quite long ago, but thanks for replying!
In fact, I reported the issue to the add-on developers, and they were able to correct the problem by themselfs.
As long as I still recall it correctly, I think it had to do with any "non resizable icons".
Unfortunately I don't know much about this subject.

So, from my point of view, the problem us solved.

Thank you again for the nice work!

Br, careca

**Comment by Geek-in-Training** [comment]
You are welcome!
