### ISSUE TITLE
What is Compact Mode in The Addon Bar (Restored)?

### ISSUE THREAD

**Issue by pcahan** [Geek-in-Training/Firefox-Addon-Bar--Restored#30]
On the Addon Bar's more information page, there is a check box for Compact Mode, but this is not documented anywhere I could find. Could you please provide an explanation of the function of this check box? (Or, in other words, what is Compact Mode?)

Note: Previous explanation was badly incomplete. A better question might be "What is the purpose of Compact Mode?"

**Comment by pcahan** [comment]
Bump

**Comment by birdie-github** [comment]
This option makes the addon bar a little less tall. That's it.

**Comment by Geek-in-Training** [comment]
Also, if you are using a Linux operating system it changes the buttons appearance slightly.
