### ISSUE TITLE
Stop working with Firefox 44 developer edition

### ISSUE THREAD

**Issue by tithom** [Geek-in-Training/Firefox-Addon-Bar--Restored#31]
The addon bar has disappeared since I have update to firefox 44.0a2

update 2 (28/01/2016) : the add-on is fixed, thanks :)

update (27/01/2016) : as we have no response from the owner of the add-on, here are two alternatives :
=> [Status-4-Evar](https://addons.mozilla.org/firefox/addon/status-4-evar/)
=> [New Add-on Bar](https://addons.mozilla.org/firefox/addon/new-add-on-bar/)

**Comment by swedeman** [comment]
Same here.

**Comment by vallovic** [comment]
Same here. Firefox 44 got into beta (which is usually the version I use) and I found out that it's not working. A fix would be awesome.

**Comment by Riajyuu** [comment]
Actually Firefox 44 stable release also breaks it here for me.

**Comment by ghost** [comment]
@Geek-in-Training 
Will you come with an update for FF44?
Is this project deprecated?

**Comment by tithom** [comment]
I am wondering what exactly do the add-on. Did it create a new bar or just enable the old one ?
After disable it and install another add-on "Toolbar buttons" ( https://addons.mozilla.org/firefox/addon/toolbar-buttons/ ), it adds a set of buttons, and one of them allows to hide / display the status bar (the button which looks like a Window in white and blue), which seems to be a similar bar than the one created with this add-on. Did this other add-on create the bar or just gives access to display it ? So for now I switch on that. I just not found how to put icons to the right of the bar.

**Comment by vallovic** [comment]
**Edited. Read the two answers bellow this one, you have two alternatives to this addon mentioned there**

**Comment by tithom** [comment]
@vallovic perhaps I missed something, but with no other addon, the "status bar" is not available in the right click on the main bar neither in the customize menu.
I have the response of my previous answer about the addon Toolbar button, "The Toggle Status Bar button in back in Firefox, and if there is no Status Bar, the button now creates it.", so indeed it creates the bar.

Finally, by reading comments on the add-on bar restored on the firefox websites, someone proposes a very similar alternative, the New Add-on bar https://addons.mozilla.org/en-US/firefox/addon/new-add-on-bar/

**Comment by vallovic** [comment]
And you're totally right, @tithom! It was a mistake of mine because I have the addon [Status-4-Evar](https://addons.mozilla.org/en-US/firefox/addon/status-4-evar/) (been using it for many years for a completely different reason than have a status bar) and that's the one that creates the status bar, so I thought that status bar was built in but hidden by default in Firefox. I apologize for that and modified my previous answer.

Well, but not everything is bad about this mistake. Now we know that we can use 2 different addons to recreate the addon bar and anyone can choose which one they want to. :smile:

**Comment by Haven667** [comment]
The new version **3.2.9-compat-fixed** is available on AMO: https://addons.mozilla.org/firefox/addon/the-addon-bar/versions

Thank you very much, dear developer. :-)

**Comment by Geek-in-Training** [comment]
@tithom @standoski @swedeman @vallovic @EMLVIRUS 

This is now fixed! https://addons.mozilla.org/firefox/addon/the-addon-bar/

@AtTheGates  Thanks for letting every one know for me! ;)

Sorry to all that it took me so long to get this done, I have not been able to even look at the addon to see how it was fairing for quite awhile.  With all the responsibilities I have here at home, it is hard to make time to work on maintaining addons.
