### ISSUE TITLE
Icons on the Addon Bar are now on the left side. Why?

### ISSUE THREAD

**Issue by roseuz** [Geek-in-Training/Firefox-Addon-Bar--Restored#6]
Icons on the addon bar are now on the left side. Why? They were on the right side. I have version 3.2 installed of the addon bar.

**Comment by Geek-in-Training** [comment]
Did you have a beta version installed? ( Upgrading from either 3.2a or 3.2b is known to cause this problem.) 

To fix it is pretty simple; just enter customize mode and drag-and-drop a flexible space to where you want it. 
Another option would be to install a earlier version again (such as 3.1) and then install the latest version.

**Comment by roseuz** [comment]
My browser crashed on it's own. I reopened it and the icons were to the left. I see that for the addon, that it was updated on May 8, 2014, so it looks like it got updated when I reopened the browser. Also, dragging the set of icons to the right is not working in Customize mode. The icons don't stick on that side. I can drag them there, but when I let go of the mouse, they are back on the left side. Like I said, they don't stick there.

**Comment by Geek-in-Training** [comment]
Oh, okay. To fix it, add a flexible space to the addon bar.
![screenshot from 2014-05-08 22 15 17](https://cloud.githubusercontent.com/assets/4809810/2924680/66846668-d739-11e3-91e9-5fd2af090318.png)
Then you should be able to move them and have them stay put.

**Comment by roseuz** [comment]
O.k. Thank you. That worked. I wish I could remember if the x was on the left or right. It seems like it's only added on for this app, as when I search online for pictures of the status bar in Firefox, I see no x. I also see that in your screenshots, the x is on the left.

**Comment by Geek-in-Training** [comment]
Good! Glad to hear it worked.
Try searching for the addon bar instead of the status bar, you'll probably find pictures with it then.
