### ISSUE TITLE
Add navigation buttons to the addon-bar

### ISSUE THREAD

**Issue by abijr** [Geek-in-Training/Firefox-Addon-Bar--Restored#8]
Don't know if this is possible. Before v29 in firefox I used to have the navigation buttons in the addon bar (back, forward, refresh), I did this by dragging them from the navigation bar to the addon bar. Do you think it might be possible to return this functionality to firefox through your addon?

**Comment by Geek-in-Training** [comment]
The _Classic Theme Restorer_ addon adds those buttons back, which could then be dragged into the addon bar. 

 The Classic Theme Restorer also adds its own addon bar, so if you want to use both be sure to get a beta build of the Classic Theme Restorer from its [version page](https://addons.mozilla.org/firefox/addon/classicthemerestorer/versions/).

**Comment by abijr** [comment]
Thanks! That worked for me.

**Comment by abijr** [comment]
I should've closed this a long time ago
