### ISSUE TITLE
Restore shortcut to hide/show Addon Bar

### ISSUE THREAD

**Issue by romaincout** [Geek-in-Training/Firefox-Addon-Bar--Restored#9]
It would be nice to have a shortcut to hide/show the Addon bar.
Ctrl+Maj+/ used to do that in Firefox <29, it will be nice to have it back.

**Comment by Geek-in-Training** [comment]
Well I am not sure what the <kbd>Maj</kbd> is supposed to be, but it does have a shorcut, <kbd>Ctrl</kbd> + <kbd>/</kbd>  (or <kbd>Cmd</kbd> + <kbd>/</kbd> on a Mac).

Which operating system are you on?

**Comment by sageross** [comment]
I have 2 Add-on Bars after installing "Addon-Bar-Restored"

THEN:

The shortcut - Ctrl+/ - is directed to OLD add-on-bar.

Is there a way to remove the redundant/old add-on bar?

**Comment by sageross** [comment]
Nevermind about my last comment. I moved all addons to the bar that the shortcut works for.

**Comment by sageross** [comment]
ACtually - I now realise - it's still broken.

It's something strange. I thought one of the bars was dominant - but it reverts and does strange things. 

I gave up. I will just ignore shortcut for this

**Comment by romaincout** [comment]
You'are right it works. Somehow it was not working at first, try to restart your firefox if you see the issue.
FYI "shift" from "ctrl+shift+/" because "shift" is needed for "/" on my french keyboard layout

**Comment by Geek-in-Training** [comment]
Oh, okay.  I didn't realize that about the French keyboard layout.

Do you still have two addon bars? I forgot to ask you earlier, but did you have two of them with only _The Addon Bar (Restored)_ installed, or did you have another addon (such as _Classic Theme Restorer_ or _The Puzzle Piece_) that adds an addon bar as well?

**Comment by sageross** [comment]
YES! Classic Theme Restorer!

YES  
On Thursday, 15 May 2014 5:05 AM, Geek in Training notifications@github.com wrote:

Oh, okay.  I didn't realize that about the French keyboard layout.
Do you still have two addon bars? I forgot to ask you earlier, but did you have two of them with only The Addon Bar (Restored) installed, or did you have another addon (such as Classic Theme Restorer or The Puzzle Piece) that adds an addon bar as well?

**Comment by sageross** [comment]
Ps. Apart from this small inconvenience - Thanks for making this script! I will recommend this to all my firefox using friends etc :)

On , Sage Durham sageross1@yahoo.com.au wrote:

YES! Classic Theme Restorer!

YES  
On Thursday, 15 May 2014 5:05 AM, Geek in Training notifications@github.com wrote:

Oh, okay.  I didn't realize that about the French keyboard layout.
Do you still have two addon bars? I forgot to ask you earlier, but did you have two of them with only The Addon Bar (Restored) installed, or did you have another addon (such as Classic Theme Restorer or The Puzzle Piece) that adds an addon bar as well?
